symfo_project_admin:
    resource: "@SymfoProjectAdminBundle/Controller/"
    type:     annotation
    prefix:   /

symfo_project_cinema:
    resource: "@SymfoProjectCinemaBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
